language: go

go:
  - "1.11"

env:
  - GOLANG_LINT_VERSION="1.12.3"

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANG_LINT_VERSION}
  - golangci-lint --version

script:
  - golangci-lint run
  - go test
