version: "3.7"
services:
  main:
    env_file: .env
    environment:
      - PORT=3000
      - GITLAB_BASE_URL
      - GITLAB_TOKEN
      - BOLT_DB_PATH
    ports:
      - "31200:3000"
    volumes:
      - ~/.gitlab-mr-coverage:/var/lib/gitlab-mr-coverage
    restart: unless-stopped
    build: .
