name: CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOLANG_LINT_VERSION: "1.20.1"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run gonalgci-lint
        uses: docker://golangci/golangci-lint:v1.22.2
        env:
          GOROOT: ""
        with:
          args: golangci-lint run -v

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test
